services:
  influxdb:
    image: "influxdb:1.3-alpine"
    expose:
      - "8086"
    ports:
      - "8086:8086"
  telegraf:
    image: "telegraf:1.3-alpine"
    links:
      - influxdb
    expose:
      - "8125"
    ports:
      - "8125:8125/udp"
    volumes:
      - "$PWD/telegraf.conf:/etc/telegraf/telegraf.conf"
  aws_lb_logs_statsd:
    image: "aws_lb_logs_statsd"
    links:
      - telegraf
    environment:
      AWS_ACCESS_KEY:
      AWS_SECRET_KEY:
      AWS_ACCOUNT_ID:
      AWS_REGION:
      AWS_BUCKET:
      AWS_LB:
      STATS_SERVER_HOST: telegraf
      STATS_SERVER_PORT: 8125
    command: "tail -f /dev/null" # Keep the container alive
version: "2"
